
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferedIpAdress: true

# separate port number for accessing the Spring boot actutator endpoints
# management:
#  server:
#    port: 9000
    
# enable all of the actuator endpoints 
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
spring:
# if Discovery server was used by admin server
#  boot:
    #Admin server
#    admin:
#      client:
#        url: http://localhost:9090
  cloud:
    #Config server
    config:
      uri: http://localhost:8888
  application:
      name: spring_boot_demoservice
server:
   port: 8080
#    port: 0 server uses random port number
      
---
spring:
   profiles: dev
   application:
      name: dev_spring_boot_demoservice
server:
   port: 9090

---
spring: 
   profiles: prod
   application:
      name: prof_spring_boot_demoservice
server: 
   port: 4431
   
---
spring:
   profiles: https
   application:
    name: https_spring_boot_demoservice
server:
  port: 443
  ssl:
     key-store: keystore.p12
     key-store-password: springboot
     keyStoreType: PKCS12
     keyAlias: tomcat
