spring:
   application:
      name: demoservice
server:
   port: 8080
#    port: 0 server uses random port number


---
spring:
   profiles: dev
   application:
      name: demoservice
server:
   port: 9090

---
spring: 
   profiles: prod
   application:
      name: demoservice
server: 
   port: 4431